PP-1072 - revisit structure
pollen-tech/pollen-web-catalog pull request #14
Opened 2023-06-21 02:23 UTC by tamatamvan

2023-06-21 02:29 UTC, echaoeoen requested changes

2023-06-21 02:29 UTC, echaoeoen commented on src/app/catalogs/[catalog_id]/page.tsx
> +  const { data } = await query<TQueryResponse>({
@tamatamvan we need to move this calling API / Appsync to integration level, I think we already talk about it, we use domain driven architecture

2023-06-21 02:33 UTC, tamatamvan commented on src/app/catalogs/[catalog_id]/page.tsx
> +  const { data } = await query<TQueryResponse>({
do you have any reference for this one? I'm following the usual implementation with app directory, where the `page.tsx` file usually handling the fetching

2023-06-21 02:36 UTC, tamatamvan commented on src/app/catalogs/[catalog_id]/page.tsx
> +  const { data } = await query<TQueryResponse>({
https://github.com/shadcn/taxonomy

2023-06-21 02:46 UTC, tamatamvan commented on src/app/catalogs/[catalog_id]/page.tsx
> +  const { data } = await query<TQueryResponse>({
If we're using usual rest-api I think it would be beneficial if we're moving the fetching into sepearate hooks/services, since every api call will request the same data. However, since we're using graphql, I think one of the benefit is that we can cherry pick the data properties that we want to fetch, that's why I think if there's any other place fetching the catalog data the query will possibly be different depends on which data properties are needed. That's what I think

2023-06-21 03:02 UTC, echaoeoen commented on src/app/catalogs/[catalog_id]/page.tsx
> +  const { data } = await query<TQueryResponse>({
nope, integration should be on separate logic, its hard for us if we want automate the test in the integration level if you place it on the page, for the properties needed, we can parametize those props,

2023-06-21 03:47 UTC, echaoeoen commented on src/app/catalogs/[catalog_id]/page.tsx
> +  const { data } = await query<TQueryResponse>({
just add service layer, the same way you did on REST API,

2023-06-21 10:00 UTC, echaoeoen commented on src/services/catalog-detail/catalog-detail.ts
> +export async function fetchCatalogDetail(catalogId: string) {
I think we will service level per domain, in this case the folder should be `catalog`, and all the service related to `catalog` will be placed on this directory

2023-06-22 02:21 UTC, echaoeoen approved these changes

2023-06-22 02:35 UTC, merged